{{- if not .Values.llama.storage.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "local-ai-hub.fullname" . }}-models
  labels:
    {{- include "local-ai-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: models
spec:
  accessModes:
    {{- toYaml .Values.llama.storage.accessModes | nindent 4 }}
  {{- include "local-ai-hub.storageClass" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.llama.storage.size }}
{{- end }}
