{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "local-ai-hub.secretName" . }}
  labels:
    {{- include "local-ai-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.secrets.postgresUser | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  llama-api-key: {{ .Values.secrets.llamaApiKey | quote }}
  gateway-api-key: {{ .Values.secrets.gatewayApiKey | quote }}
  webui-secret-key: {{ .Values.secrets.webuiSecretKey | quote }}
  openwebui-database-url: {{ printf "postgresql://%s:%s@%s-postgres:%v/open_webui" (.Values.secrets.postgresUser | urlquery) (.Values.secrets.postgresPassword | urlquery) (include "local-ai-hub.fullname" .) .Values.postgres.service.port | quote }}
  hermes-api-key: {{ .Values.secrets.hermesApiKey | quote }}
  hermes-dashboard-username: {{ .Values.hermes.dashboard.username | quote }}
  hermes-dashboard-password: {{ .Values.hermes.dashboard.password | quote }}
{{- end }}
