#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    destination = ROOT / path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")


def patch_hubctl() -> None:
    path = "ops/hubctl.py"
    text = read(path)
    marker = '''    values: dict[str, Any] = {\n        "models": {},\n        "experiences": catalog.get("experiences", {}),\n'''
    replacement = '''    values: dict[str, Any] = {\n        "catalog": catalog,\n        "models": {},\n        "experiences": catalog.get("experiences", {}),\n'''
    if '"catalog": catalog,' not in text:
        if marker not in text:
            raise RuntimeError("catalog_to_k8s_values mapping was not found")
        text = text.replace(marker, replacement, 1)
    write(path, text)


def patch_helm_values() -> None:
    path = "deploy/helm/local-ai-hub/values.yaml"
    text = read(path)
    if "\ncatalog: {}\n" not in text:
        marker = "models: {}\n"
        if marker not in text:
            raise RuntimeError("Helm models placeholder was not found")
        text = text.replace(
            marker,
            marker
            + "\n# Full effective catalog generated by ./hub catalog k8s-values.\n"
            + "# The fallback chart configuration remains valid when this is empty.\n"
            + "catalog: {}\n",
            1,
        )
    write(path, text)


def patch_helm_schema() -> None:
    path = ROOT / "deploy/helm/local-ai-hub/values.schema.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    properties = document.setdefault("properties", {})
    properties.setdefault("catalog", {"type": "object"})
    path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def write_gateway_configmap() -> None:
    write(
        "deploy/helm/local-ai-hub/templates/gateway-configmap.yaml",
        '''{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local-ai-hub.fullname" . }}-gateway
  labels:
    {{- include "local-ai-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
data:
  catalog.resolved.json: |
{{ if .Values.catalog }}
{{ toPrettyJson .Values.catalog | nindent 4 }}
{{ else }}
    {
      "version": 2,
      "backends": {
        "local-llama": {
          "kind": "llama.cpp",
          "enabled": {{ .Values.llama.enabled }},
          "base_url": "http://{{ include "local-ai-hub.fullname" . }}-llama:{{ .Values.llama.service.port }}",
          "api_key_env": "LLAMA_API_KEY",
          "coordinator": "explicit",
          "serialize_requests": true,
          "endpoints": {
            "chat": "/v1/chat/completions",
            "responses": "/v1/responses",
            "completions": "/v1/completions",
            "infill": "/infill",
            "embeddings": "/v1/embeddings",
            "rerank": "/v1/rerank"
          }
        }
      },
      "models": {
        {{- $first := true }}
        {{- range $id, $model := .Values.models }}
        {{- if $model.enabled }}
        {{- if not $first }},{{ end }}
        {{ $id | quote }}: {
          "display_name": {{ default $id $model.displayName | quote }},
          "enabled": true,
          "backend": {{ default "local-llama" $model.backend | quote }},
          "upstream_model": {{ default $id $model.upstreamModel | quote }},
          "priority": {{ default 0 $model.priority }},
          "capabilities": {{ toJson (default (dict "chat" (dict)) $model.capabilities) }},
          "features": {{ toJson (default (dict) $model.features) }},
          "artifact": {"kind": "container_path", "path": {{ $model.containerPath | quote }}},
          "runtime": {}
        }
        {{- $first = false }}
        {{- end }}
        {{- end }}
      },
      "experiences": {{ toJson (ternary .Values.experiences .Values.hubProfiles (not (empty .Values.experiences))) }}
    }
{{ end }}
{{- end }}
''',
    )


def write_release_notes() -> None:
    write(
        "docs/RELEASE_NOTES_V0.3.0.md",
        """# Agent UI 0.3.0 — Generic Platform

Agent UI 0.3 removes preferred-model assumptions from the distributable project and
turns the system into a capability-oriented control plane for operator-owned models.

## Core changes

- Empty installations start successfully and report `setup_required`.
- Models are registered against backends and declare capabilities explicitly.
- Stable experiences (`chat`, `code`, `story`, `image`, `agent`, and retrieval
  workloads) select compatible deployments by priority or explicit pinning.
- Reasoning/effort support is declared per model and can map client values to any
  upstream body field or chat-template argument.
- The gateway supports chat, Responses, completions, infill, embeddings, reranking,
  and image-generation routes.

## Existing model storage

The model artifact contract supports:

- Agent UI-managed copies;
- read-only host file or directory mounts;
- existing Docker volumes;
- operator-provided container paths;
- existing Kubernetes PVCs;
- explicit Kubernetes hostPath sources;
- API-served models with no local artifact.

Compose mount overrides and Helm values are generated from the same effective catalog.
External storage remains independently owned and is not silently copied or deleted.

## AI-first setup

A setup agent can discover candidates, produce a schema-valid overlay, run a dry plan,
request operator approval, apply the catalog, start the stack, and verify setup status.
The live gateway exposes read-only setup inspection but cannot mutate host mounts or
credentials through a chat request.

## Compatibility

The v0.3 gateway retains legacy Local AI Hub headers and version-1 profile loading for
migration. New installations should use the version-2 catalog and `X-Agent-UI-*`
headers.

## Validation expectations

A release candidate must pass Python tests with branch coverage, Ruff, Python compile,
shell syntax, toolbox and gateway image builds, generated Compose validation, Helm
lint, default chart rendering, and existing-PVC chart rendering.
""",
    )


def clean_one_shot_artifacts() -> None:
    for relative in (
        "ops/v03_finalize.py",
        "ops/v03_release_gate.py",
        ".github/workflows/v03-finalize.yml",
        ".github/workflows/v03-release-gate.yml",
        ".v03-finalize-trigger",
        ".v03-release-gate-trigger",
    ):
        (ROOT / relative).unlink(missing_ok=True)


def main() -> None:
    patch_hubctl()
    patch_helm_values()
    patch_helm_schema()
    write_gateway_configmap()
    write_release_notes()
    clean_one_shot_artifacts()


if __name__ == "__main__":
    main()
