#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def write(relative: str, content: str) -> None:
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def add_local_backend_environment_override(relative: str) -> None:
    text = read(relative)
    if "base_url_env: LLAMA_BASE_URL" in text:
        return
    marker = "    base_url: http://llama:8080\n"
    if marker not in text:
        raise RuntimeError(f"local llama backend marker missing in {relative}")
    write(relative, text.replace(marker, marker + "    base_url_env: LLAMA_BASE_URL\n", 1))


def ensure_k8s_catalog_generation() -> None:
    path = "ops/hubctl.py"
    text = read(path)
    if '"catalog": catalog,' not in text:
        marker = '''    values: dict[str, Any] = {\n        "models": {},\n        "experiences": catalog.get("experiences", {}),\n'''
        replacement = '''    values: dict[str, Any] = {\n        "catalog": catalog,\n        "models": {},\n        "experiences": catalog.get("experiences", {}),\n'''
        if marker not in text:
            raise RuntimeError("catalog_to_k8s_values mapping missing")
        text = text.replace(marker, replacement, 1)
        write(path, text)

    values_path = "deploy/helm/local-ai-hub/values.yaml"
    values = read(values_path)
    if "\ncatalog: {}\n" not in values:
        marker = "models: {}\n"
        if marker not in values:
            raise RuntimeError("Helm model map marker missing")
        values = values.replace(
            marker,
            marker
            + "\n# Full effective catalog generated by the Agent UI control plane.\n"
            + "catalog: {}\n",
            1,
        )
        write(values_path, values)

    schema_path = ROOT / "deploy/helm/local-ai-hub/values.schema.json"
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    schema.setdefault("properties", {}).setdefault("catalog", {"type": "object"})
    schema_path.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")


def ensure_gateway_image_version() -> None:
    path = "deploy/docker/gateway.Dockerfile"
    text = read(path)
    text = text.replace("local-ai-hub", "agent-ui")
    write(path, text)


def remove_one_shot_files() -> None:
    for relative in (
        "ops/v03_finalize.py",
        "ops/v03_release_gate.py",
        "ops/v03_final_check.py",
        ".github/workflows/v03-finalize.yml",
        ".github/workflows/v03-release-gate.yml",
        ".github/workflows/v03-final-check.yml",
        ".v03-finalize-trigger",
        ".v03-release-gate-trigger",
        ".v03-final-check-trigger",
    ):
        (ROOT / relative).unlink(missing_ok=True)


def main() -> None:
    add_local_backend_environment_override("config/models/catalog.yaml")
    add_local_backend_environment_override("config/gateway/profiles.yaml")
    ensure_k8s_catalog_generation()
    ensure_gateway_image_version()
    remove_one_shot_files()


if __name__ == "__main__":
    main()
